theme: jekyll-theme-architect

.
├── about.md          # => http://example.com/about.html
├── pictures.html    # folder containing pages
│   └── extra_pictures.html       # => http://example.com/documentation/doc1.html
├── contact.html 
├── portfolio.html            # folder containing pages
└── resume.html 
